project:
  type: website
  output-dir: docs

website:
  title: "Jakub Stauber"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - publications.qmd
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



