---
title: Publications
---

## Peer-reviewed Articles
Kofroň J and Stauber J (2024) Spending on personnel or equipment: panel analysis of military expenditures in the NATO countries 2005–2019. European Security, 0 (0): 1–25. DOI: 10.1080/09662839.2023.2293075. ([replication](https://doi.org/10.6084/m9.figshare.c.6729201.v1))

Kofroň J and Stauber J (2023) The impact of the Russo-Ukrainian conflict on military expenditures of European states: security alliances or geography? Journal of Contemporary European Studies 31(1): 151–168. DOI: 10.1080/14782804.2021.1958201.

Perottino M, Stauber J and Šárovec D (2020) Reconstruction of the state: Lobbying against political corruption in the Czech Republic. Journal of Public Affairs 20(1): e2054. DOI: 10.1002/pa.2054.

Cirhan T and Stauber J (2018) Online supporter and registered sympathiser as alternatives to a regular party member. East European Politics 34(4): 458–482. DOI: 10.1080/21599165.2018.1532410.

Stauber J (2017) Institutionalization of nationalized party system: The Czech case. Acta Politologica 9(3): 46–65.

Stauber J (2015) Organizační vývoj nových politických stran v České republice pohledem teorie institucionalizace. Acta Politologica 7(2): 133–155.

Stauber J (2015) Party Institutionalisation in the Czech Republic: Towards a New Measurement of the Theoretical Concept. Středoevropské politické studie XVII(3–4): 249–275.

## Chapters
Stauber J (2019) Party Institutionalisation in the Czech Republic. In: Harmel R and Svasand LG (eds) Institutionalisation of Political Parties: Comparative Cases. London: ECPR Press, pp. 215–238.

## Datasets
Parizek M and Stauber J (2024) The Global Media Visibility of States Dataset V1. DOI: 10.17605/OSF.IO/2X9R3. ([download](https://osf.io/2x9r3/))
